events:
  - type: Mail
    subType: Single
    impl: ./srv/EventQueueMail
    load: 10
    parallelEventProcessing: 5

periodicEvents:
  - type: HealthCheck
    subType: DB
    impl: ./srv/EventQueueHealthCheckDb
    load: 80
    transactionMode: alwaysRollback
    interval: 15
