### Create Task
POST http://localhost:4004/odata/v4/process/C_ClosingTask
Content-Type: application/json
Authorization: Basic alice@wonderland.com alice

{
  "description": "testTask"
}

### Process Task
POST http://localhost:4004/odata/v4/process/C_ClosingTask(b039d6bd-7861-4d72-9246-cc244485cd2a)/process
Content-Type: application/json
Authorization: Basic alice@wonderland.com alice

{
}

### Get Task
GET http://localhost:4004/odata/v4/process/C_ClosingTask(4bee739c-398c-4620-ae0d-4b451d2dd227)
Content-Type: application/json
Authorization: Basic alice@wonderland.com alice

{
  "description": "testTask"
}
