### Create Task
POST http://localhost:4004/odata/v4/process/C_ClosingTask
Content-Type: application/json
Authorization: Basic alice@wonderland.com alice

{
  "description": "testTask"
}

### Process Task
POST http://localhost:4004/odata/v4/process/C_ClosingTask(88c2a7b8-5e1b-43f1-b96a-ef78cdf0f165)/process
Content-Type: application/json
Authorization: Basic alice@wonderland.com alice

{
}

### Get Task
GET http://localhost:4004/odata/v4/process/C_ClosingTask(4bee739c-398c-4620-ae0d-4b451d2dd227)
Content-Type: application/json
Authorization: Basic alice@wonderland.com alice

{
  "description": "testTask"
}
