source "https://rubygems.org"

# https://github.com/ruby/ruby
ruby ">= 3.4.7"

# https://jekyllrb.com/docs/installation/
gem "jekyll", "~> 4.3"

# Ruby 4.0 removed these from default gems
gem "logger"
gem "csv"

# https://github.com/just-the-docs/just-the-docs/releases
gem "just-the-docs", "~> 0.10.1"
