# This workflow will protect the main branch by testing and linting new PRs and commits

name: Main CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    name: test - node.js ${{ matrix.node-version }}
    steps:
      - name: "unique id for hana schema"
        id: generateId
        run: echo "id=$(uuidgen)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --package-lock
      - run: npm run test:deploySchema
        env:
          SCHEMA_GUID: ${{steps.generateId.outputs.id}}
          HANA_DB_CREDENTIALS: ${{secrets.HANA_DB_CREDENTIALS}}
      - run: npm run test:prepare
      - run: npm run test:unit
      - run: npm run test:integration
        env:
          GITHUB_ACTION_HANA: true
          SCHEMA_GUID: ${{steps.generateId.outputs.id}}
          HANA_DB_CREDENTIALS: ${{secrets.HANA_DB_CREDENTIALS}}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci --package-lock
      - run: npm run lint:ci

  cleanSchemas:
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci --package-lock
      - run: npm run test:cleanSchemas
        env:
          HANA_DB_CREDENTIALS: ${{secrets.HANA_DB_CREDENTIALS}}
