# This workflow will protect the main branch by testing and linting new PRs and commits

name: Main CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
        cds-old-db-service: [true, false]

    name: test - node.js ${{ matrix.node-version }} - new cds db service enabled ${{ matrix.cds-old-db-service }}
    steps:
      - name: "unique id for hana schema"
        id: generateId
        run: echo "id=$(uuidgen | tr '[:lower:]' '[:upper:]')" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --package-lock
      - run: npm run test:deploySchema
        env:
          SCHEMA_GUID: ${{steps.generateId.outputs.id}}
          HANA_DB_CREDENTIALS: ${{secrets.HANA_DB_CREDENTIALS}}
      - run: npm run test:prepare
      - run: npm run test:unit
        env:
          OLD_DB_SERVICE: ${{ matrix.cds-old-db-service }}
      - run: npm run test:integration
        env:
          GITHUB_ACTION_HANA: true
          SCHEMA_GUID: ${{steps.generateId.outputs.id}}
          HANA_DB_CREDENTIALS: ${{secrets.HANA_DB_CREDENTIALS}}
          OLD_DB_SERVICE: ${{ matrix.cds-old-db-service }}
      - run: npm run test:cleanSchemas
        if: always()
        env:
          HANA_DB_CREDENTIALS: ${{secrets.HANA_DB_CREDENTIALS}}
          SCHEMA_GUID: ${{steps.generateId.outputs.id}}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci --package-lock
      - run: npm run lint:ci
